#用户权限授权服务配置(开发环境)

env: dev
server:
  port: 8888
  servlet:
    session:
      timeout: 600
spring:
  application:
    name: uaa
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 100
    min-evictable-idle-time-millis: 1800000
    min-idle: 10
    password: root
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    url: jdbc:mysql://127.0.0.1:3306/rising_authority?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    validation-query: select 1
  jackson:
    default-property-inclusion: non_null
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  redis:
    database: 8
  session:
    store-type: none

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:20000/eureka/}
  instance:
    instance-id: ${spring.application.name}:${server.port}
    ip-address: 127.0.0.1
    prefer-ip-address: true
logging:
  level:
    com:
      rising: debug
rising:
  security:
    code:
      sms:
        url: /sys/admin/me1
    oauth2:
      clientId: admin
      clientSecret: admin
    social:
      filterProcessesUrl: /qqLogin
      qq:
        app-id: 100550231
        app-secret: 69b6ab57b22f3c2fe6a6149274e3295e
        providerId: callback.do
      weixin:
        app-id: wxd36bc5aa1c6b4497
        app-secret: eb58e323e57ac9a908ea5ca1d75c2298
        providerId: weixin