@startuml

class Admin
class Resource
class Role
class RoleAdmin
class RoleResource
class Organization
class OrganizationAdmin
class RoleOrganization

Admin --* RoleAdmin : admin >
RoleAdmin *-- Role: have 4 >

@enduml