@startmindmap
'https://plantuml.com/mindmap-diagram

title 网络货运模块功能

* <&flag>网络货运
** <&globe>车辆管理(已完成)
*** 添加车辆
*** 车辆审核
*** 车辆编辑
*** 证件上传(行驶证)
*** 上传车辆信息(交通厅平台)
** <&graph>司机管理(已完成)
*** 添加司机
*** 添加编辑
*** 证件上传(驾驶证/身份证)
*** 上传司机信息(交通厅平台)
** <&pulse>货物管理
*** 发布货物信息
*** 修改货物信息
*** 删除货物信息
** <&people>派单管理
*** 添加派车
*** 编辑派车
*** 运价成本核算
*** 审核
*** 回单
*** 删除派车
** <&people>运单管理
*** 上传运单(交通厅平台)
** <&people>清分结算管理
*** 财务审核
*** 结算打款
** <&people>资金流水管理
*** 上传(交通厅平台)
** <&star>系统管理
*** 用户管理(已完成)
**** 添加用户
**** 编辑用户
**** 删除用户
***  企业管理(进行中)
**** 企业添加(菜单权限)
**** 企业编辑(菜单权限)
**** 企业删除(禁用)
***  角色管理(已完成)
**** 添加角色
**** 删除角色
**** 编辑角色
***  菜单管理(已完成)
**** 添加菜单
**** 编辑菜单
**** 删除菜单
**** 菜单api授权

** 日志管理(进行中)
*** 登录日志
*** 业务日志

@endmindmap
