server:
  port: 8400
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:  #https://gitee.com/ynzl/internet-freight-platform.git
          uri: https://gitee.com/ynzl/internet-freight-platform
          username: 18788523442
          password: 3344520myy


eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:20000/eureka/}
  instance:
    prefer-ip-address: true  #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例id