spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.24.43.129:3306/internet_freight?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root@123456
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      ##打印sql语句时是否格式化
      #spring.jpa.properties.hibernate.format_sql=true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true


